global using Microsoft.Extensions.Logging;
global using System.ComponentModel;
global using System.Runtime.CompilerServices;
global using System.Windows.Input;
global using System.Text;
global using Newtonsoft.Json;
global using Voxerra.Services.Authenticate;
global using Voxerra.ViewModels;
global using Voxerra.Models;
global using System.Web;
global using ServiceProvider = Voxerra.Services.ServiceProvider;
global using Microsoft.AspNetCore.SignalR;
global using Microsoft.AspNetCore.SignalR.Client;
global using Voxerra.Services.ChatHub;
global using Voxerra.Services.Notification;
global using Voxerra.Pages;